# Generated by Django 2.1.2 on 2018-10-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pergame2018',
            table='PerGame2018',
        ),
    ]
